apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: flux-system
spec:
  interval: 1m
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.23.x     # or whatever version you want
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
  install:
    createNamespace: true   # 👈 this makes sure cnpg-system is created
  targetNamespace: cnpg-system
