apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-database
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/minikube/infra/database
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: flux-system
  timeout: 2m
